@url = https://organic-guacamole-4xpqj999r4j2j4qw-8080.app.github.dev
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJGaWxtZXMgQVBJIiwic3ViIjoiYWRtaW4iLCJleHAiOjE3NjM0OTM5MjZ9.hn6DMk0c2wCMVeO4KxOPxu86LUKu7hHcGEXd_rItlqE

GET {{url}}/alunos
Authorization: Bearer {{token}}

###
POST {{url}}/alunos
Content-Type: application/json

{
    "nome" : "Carlos Costa"
}

###
PUT {{url}}/alunos/3
Content-Type: application/json

{
    "nome" : "Daniel Vargas"
}

###
DELETE {{url}}/alunos/3